### ISSUE TITLE
Issue with first load on subpages

### ISSUE THREAD

**Issue by jorkvist** [lokecarlsson/gridsome-starter-bootstrap#10]
If i go to https://gridsome-starter-bootstrap.loke.dev/contact i get a 301 respons to 
https://gridsome-starter-bootstrap.loke.dev/contact/ 

But on https://gridsome-starter-bootstrap.loke.dev/contact/ no links/functionality are working. 

Tested in latest Chrome. 

If i browse from https://gridsome-starter-bootstrap.loke.dev to /contact it works correct.

**Comment by lokecarlsson** [comment]
Can confirm, same thing happens for me! Thank you for reporting this, I will check it out.

**Comment by lokecarlsson** [comment]
Fixed with Netlify config.
