### ISSUE TITLE
forestry dev server error

### ISSUE THREAD

**Issue by lorvent** [LokeCarlsson/gridsome-starter-bootstrap#7]
Hello,

when i try to boot forestry dev server, getting following error

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/vuepress'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

can you pls tell me how to fix?

thanks.

**Comment by LokeCarlsson** [comment]
I have never tried forestry dev server. Since forestry is not supporting gridsome officially, you need to use vuepress which seem to be the problem somehow. Cant say how you can fix it since i didnt even know forestry had a dev server.

**Comment by lorvent** [comment]
actually conf working fine with netlify but not on forestry

when i try other gridsome projects, its working fine though.

**Comment by LokeCarlsson** [comment]
Either way, I need more information if I should be able to help you.

**Comment by lorvent** [comment]
hmm, honestly i can live without forestry dev server....

but i already passed you the info i.e. error msg

if you want more info, probably you need to try repo on forestry then may be you can spot something (which i am overlooking).

thanks.

**Comment by JonathanFager** [comment]
Having the same error.
Forestry preview servers won't work.

**Comment by LokeCarlsson** [comment]
@lorvent @JonathanFager Issues are solved and I got the preview working. You might have to remove and add the page to forestry for all the configs to go through. I haven't used this feature myself before, hence why I didn't had it working before.
